server:
  port: 9002
  context-path: /client1

security:
  oauth2:
    client:
      clientId: foo
      clientSecret: foosecret
      accessTokenUri: http://localhost:9000/authserver/oauth/token
#      SSO跳转页面
      userAuthorizationUri: http://localhost:9000/authserver/oauth/authorize
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://localhost:9000/authserver/user




